### ISSUE TITLE
Wrong answer after search

### ISSUE THREAD

**Issue by Nosfe99** [NationalSecurityAgency/qgis-searchlayers-plugin#10]
QGIS 3.6
Search Layer 3.0.1

Hi,

I'm trying to use your plugin, because it's really what I need. But I have a problem with it.

When I'm searching something on it (on France map), that find it, and work very goodly. But when I click on the results for go to see it, that send me in the middle of Nigeria (??). Each time...
I don't know why. And as I didn't found any way to configure the plugin, I dont know what to do.

Do you have a solution? Or perhaps it's just a little bug?

Thank you for your future answer.

Best regards

**Comment by hamiltoncj** [comment]
@Nosfe99 
That is strange behavior. I have not seen it. Try upgrading to QGIS 3.8.2 and see if that fixes it. If not do you have a small QGIS project that exhibits this behavior that I could try? I have not been able to reproduce this anomaly.

**Comment by Nosfe99** [comment]
Wow! Very sorry, it's totally my fault! That was a problem of bad SCR config.
So, now, it's working perfectly, and very useful! Thanks a lot ^^
