### ISSUE TITLE
No Search Layer Toolbar Icon - QGIS 3.10 LTR & QGIS 3.16.3 

### ISSUE THREAD

**Issue by robdouglasnz** [NationalSecurityAgency/qgis-searchlayers-plugin#11]
Search Layer toolbar icon not displaying.- QGIS 3.10 LTR & QGIS 3.16.3 - MacOS 11.1
There used to be one.

**Comment by hamiltoncj** [comment]
@robdouglasnz  Nothing has changed since last year. I am not sure what is wrong. It show up properly on my windows QGIS. Make sure you haven't disabled the Plugins Toolbar. Right mouse click anywhere in the toolbar area and you will see all of the toolbars. Make sure "Plugins Toolbar" is checked.

**Comment by robdouglasnz** [comment]
Thank you for the reply,

Previously it was not showing up in the Plugin Toolbar on either 3.16 or LTR. After removing and reinstalling and some reboots it has now appeared. Not sure why it dropped off.

I appreciate your help and work on QGIS project.

Rob
