### ISSUE TITLE
Adding "visible layer"

### ISSUE THREAD

**Issue by jimvakis** [NationalSecurityAgency/qgis-searchlayers-plugin#12]
It would be nice to have the choice of searching only what is been viewed in the map, with an option called <Visible layers> (Arcgis has this option...).
This way the engine will search only the visible data thus reducing the time and the final results.

**Comment by hamiltoncj** [comment]
@jimvakis 
I think what you are asking is to only search those features that are visible within the canvas window. Is that correct? I looked at what it would take to implement this and I think it would be easy. If I misunderstood your suggestion let me know I would probably add a check box to search the visible canvas area only. It might take me a week to get to this, but I don't think it will take much time coding.

**Comment by jimvakis** [comment]
Correct! This is the scenario.I want to find features that are visible in
the canvas map.
You have to take in mind:
1) What layers are checked in Layer Panel,
2) Scale dependent visibility of layer.

You can either add a check box (as you suggest) or you could add the option
in "Search layers" (see attached photos). I think this would be better,
(ARCGIS has this option like that) as it won't burden the main window with
an "other box".
Great work!!!
Greetings from Athens, Greece!

Στις Τρί 22 Φεβ 2022 στις 11:18 μ.μ., ο/η C Hamilton <
***@***.***> έγραψε:

**Comment by hamiltoncj** [comment]
@jimvakis Unfortunately when you use email to reply the photos do not come through. You have to go specifically to github and attach them in the Issue page.

**Comment by jimvakis** [comment]
![qgis](https://user-images.githubusercontent.com/100127185/155327498-77b2a41a-612a-419b-8c9a-76b2eaa00753.jpg)
![ARCGIS](https://user-images.githubusercontent.com/100127185/155327503-f7c406c0-650f-46dd-99b3-b4af1fc9b4b8.jpg)

**Comment by hamiltoncj** [comment]
I released Search Layers 3.0.6. I decided to add both a <Visible layers> layer selection option as well as a "Constrain search to canvas extent" check box. There was space to add them without taking up more room. Let me know what you think.

**Comment by jimvakis** [comment]
It is working great! (Needs a little correction the word "visiable").

It would be nice after the results, when I select a layer, this to flash
instantly (like qgis is doing).

Στις Πέμ, 24 Φεβ 2022, 21:45 ο χρήστης C Hamilton ***@***.***>
έγραψε:

**Comment by hamiltoncj** [comment]
Oops. Sorry about the misspelling. I have another organization who is interested in having something like the flash. Right now I am selecting the clicked on features in the vector layer which causes them to be highlighted, but if they are underneath other features you won't see them. If I do the flashing as an overlay, they will always be visible. There can be unintended consequences when features in the vector layer are selected, so I am thinking of no longer doing that. Unless you see a need for it. This will take some time to make these changes.

Thanks you for your suggestions.
