### ISSUE TITLE
Are there any plans to make it multilingual?

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [NationalSecurityAgency/qgis-searchlayers-plugin#13]
Nice to meet you.
I am a user from Japan.
I have been using your site on a daily basis in my business.
Many of the users around me have a great deal of resistance to the English notation, and I would like to try to convert it to Japanese.
It is OK to change the ui file and each time, but in the long run, I would be glad if you could make a language file.

**Comment by hamiltoncj** [comment]
@yamamoto-ryuzo This could be done. I have done it with the Shape Tools plugin which a person translated into Chinese. In that case the problem that I face is that the translation has never been updated and it is not something I can do.

I could implement the language code for this plugin, but you would need to do the translation. I would need to generate the English .ts file and then you could go from there. Is that something you can do? You would need to be able to use Qt Linguist. Here are QGIS instructions:

https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#translation

**Comment by yamamoto-ryuzo** [comment]
I checked about Qt Linguist.
It is somewhat like a text editor for .TS files?
I think I can probably handle it, so I don't think it will be a problem.
Thank you in advance.

**Comment by hamiltoncj** [comment]
@yamamoto-ryuzo I believe I have updated the code base to support other languages. There is a file at i18n/searchLayers_ja.ts. I think ja is the correct code for Japanese. Please do the translation with Qt Linguist. You can either do a pull request when you are done or attach the file here. Then we will see if the process worked.

**Comment by yamamoto-ryuzo** [comment]
Thank you very much.
I am off tomorrow and the day after tomorrow, so I will try to do this as soon as possible.
