### ISSUE TITLE
Realization of custom settings for each project

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [NationalSecurityAgency/qgis-searchlayers-plugin#17]
I apologize for the sudden PULL request the other day.
In addition, I was not sure how to use the system and thought it was two sources to PULL, but they were combined.
Now, here are my suggestions.
Thank you in advance for your consideration.
I have set up a separate repository to check the operation.
Please let me know if there is anything that needs to be fixed.
In addition, I plan to add new features, etc. sequentially as time permits.
https://github.com/yamamoto-ryuzo/yr-qgis-searchlayers-plugin/
I am new to this kind of work, so please let me know how to go about it.
------------ Functional Overview ------------
 By specifying a layer name in the variable 'searchlayers-plugin' in the project file, only the specified layer can be searched.  
#### ・normal
 ![image](https://user-images.githubusercontent.com/86514652/181909319-7436b72d-5c2f-49b0-b5be-2c8482644a4e.png)  
#### ・set 'searchlayers-plugin' "test1,test3,test10'  
![image](https://user-images.githubusercontent.com/86514652/181909555-981fb82a-ce43-4255-b674-de02511fd0c0.png)  
#### ・result:  
 ![image](https://user-images.githubusercontent.com/86514652/181909585-7cc2ad58-779e-409a-9fcb-7f1dd8f5dfce.png)

**Comment by hamiltoncj** [comment]
Sorry I haven't responded sooner. I have been busy with a paper justifying the use of QGIS in our organization. There is the possibility that I may not be allowed to do any more QGIS plugin development. 

My question is why would you want to have a variable of the layers you want to search? Why not just select them in the QGIS layer panel and search on them? I don't think the capability you are asking for would be approved to have added to Search Layers.

If you download the new i18n/searchLayers_ja.ts file you can translate <All Layers>, <Selected Layers>, and <Visible Layers> strings. Those I can add and update.

**Comment by yamamoto-ryuzo** [comment]
Thank you for your response.
It is perfectly fine if you answer at your own pace.

We are currently working on the search functionality, both with the search plugin we are creating and with this great plugin.
We are wondering if it would be possible to consolidate to this plugin.
The first step is to make it Japanese.

The second part is to simplify the search screen.
The reason is that we have dozens of layers that we don't need as search targets, but often only a few that we need.
In such cases, we would like to customize it because it is difficult to find the selection target in its current state.

The future proposal is also realistic and has already been implemented in our plugin.
If it suits your purpose, we would be happy to implement it.

If it looks good, I will make a pull request.

**Comment by yamamoto-ryuzo** [comment]
Thank you for your continued support regarding the translation.
Pull requests for ts files only.

**Comment by hamiltoncj** [comment]
I think the changes are reasonable. As far as I can tell the only changes you have made is to searchDialog.py and i18n\searchLayers_ja.ts. You have a different readme.md and several other files created by something, which don't affect the plugin. Do you want me to just replace the two files without you needing to do a pull request? That might prevent some unnecessary files getting merged.

**Comment by yamamoto-ryuzo** [comment]
That is correct.
In fact, I was baffled when I made a modified PULL request for another plugin in my environment and the whole thing was replaced.
I thought I should learn more about how to PULL in different working environments.
As a result, I now set up a separate repository from the PULL to modify it.

**Comment by yamamoto-ryuzo** [comment]
The search we use, which we are currently considering integrating, was recently open sourced and is in the process of being generalized.
We will consider it again when that one is completed.
https://github.com/yamamoto-ryuzo/GEO-search-plugin

**Comment by hamiltoncj** [comment]
I am not used to working with others on this so this is all new to me as well. Since I came from a C/C++ background I think there is probably a better way to manage the python code rather than using a makefile. It is all a learning process. 

Are you planning on doing a pull request with those two files that have changed or do you want me to drop them into my code repo?

**Comment by yamamoto-ryuzo** [comment]
[do you want me to drop them into my code repo?]
　I'll study it next time.
First of all, I would like to make a PULL request for the realization of custom settings for each project, which is the original purpose of this project.
We will consider other feature proposals as soon as the plugin we have created is generalized.
Thank you in advance.

**Comment by yamamoto-ryuzo** [comment]
https://github.com/NationalSecurityAgency/qgis-searchlayers-plugin/pull/18
