### ISSUE TITLE
Possibility to use search fields option with "All Layers" option selected

### ISSUE THREAD

**Issue by rnousia** [NationalSecurityAgency/qgis-searchlayers-plugin#22]
Hi! And thank you for the plugin, this seems to be a very useful tool.

I found this plugin while trying to search for a way to loop through features on multiple layers. This plugin would be quite optimal for our need but there is one caveat: I could not find a way to specify search field name for multiple layers.

Short background: our users have 70+ layers in QGIS and they need to find features with a certain attribute value. All the layers have a common field which needs to be searched. Unfortunately the search value is too common value found in all the fields (like "1" or "a") so currently Search Layers plugin would result 2000+ results and only a minor subset would be the actual features the users are interested in.

Would it be possible to list all the fields in the "Search Fields" combobox even when all the layers are selected? This would of course mean that the list would be quite long but as it is possible to search the list by typing (plus use arrow keys I think?) I think it might not be too much? Or maybe the list could also be in alphabetical order and have a scroll bar?

I tested this a bit by modifying initFieldList-method and it seems to work just with this change (but I just tested with my case if it works):

```python
    def initFieldList(self):
        selectedLayer = self.layerListComboBox.currentIndex()
        self.searchFieldComboBox.clear()
        self.searchFieldComboBox.addItem(tr('<All Fields>'))

        unique_field_names = set()
        layers: List[QgsVectorLayer] = []

        # Following if structure copied from https://github.com/NationalSecurityAgency/qgis-searchlayers-plugin/blob/master/searchDialog.py#L247-L259
        # Could be own method get_search_layers() etc.
        if selectedLayer == 0:
            # Include all vector layers
            layers = QgsProject.instance().mapLayers().values()
        elif selectedLayer == 1:
            # Include all selected vector layers
            layers = self.iface.layerTreeView().selectedLayers()
        elif selectedLayer == 2:
            # This is for visiable layers and content
            layer_trees = QgsProject.instance().layerTreeRoot().findLayers()
            layers = []
            for lt in layer_trees:
                if lt.isVisible():
                    layers.append(lt.layer())
        else:
            layers = [self.searchLayers[selectedLayer]]

        for layer in layers:
            for field in layer.fields():
                unique_field_names.add(field.name())
        
        # Add unique field names to combobox
        self.searchFieldComboBox.setEnabled(True)
        for field_name in unique_field_names:
            self.searchFieldComboBox.addItem(field_name)
```

Then it would look like something like this (layer1 and layer2 have a common field "common_field" that needs to be searched):
![kuva](https://github.com/NationalSecurityAgency/qgis-searchlayers-plugin/assets/12234068/8f496b71-3da0-4a90-a54f-a2353b736250)

We are also willing to make a pull request if this is something that would add value to other users and if it helps.

**Comment by hamiltoncj** [comment]
I like this. You are addressing one flaw that I knew existed, but never got around to. I think the field names probably should be in alphabetic order especially where it would be spanning multiple layers and ideally should have a scrollbar if too large. I can test it a little more. I guess it is your choice whether you want to do a pull request or have me use the code you have here. Is there something more that you would want to do first?

**Comment by rnousia** [comment]
Good to hear! I could first check the workflow with plugin for our case with our users and ask some more feedback. And then make the pull request if this is ok for you? But I think the list of fields in alphabetical order would work at least for us, feel free to suggest other solutions. 

I'll get back to this in few weeks.

**Comment by rnousia** [comment]
Sorry took a bit longer than I planned but created a PR for this feature now. Feel free to modify!
