### ISSUE TITLE
Plugin no longer published on QGIS server?

### ISSUE THREAD

**Issue by Fabien98** [NationalSecurityAgency/qgis-searchlayers-plugin#3]
Hello,

It seems that this plugin is no longer available trhough the QGIS plugin manager?
https://plugins.qgis.org/plugins/layersearch/
_(Error 404 with the above link)_
Is it normal?

**Comment by hamiltoncj** [comment]
The plugin had not been approved so I removed it. I don't think anyone could see it other than those who manage the plugins. I might try updating it and resubmitting it. There was interest in merging some of my functionality into one of the other search plugins, but that has never happened. What do you think I should do?

**Comment by Fabien98** [comment]
I've read about the other thread #1 
I agree with you about different purposes of "Quick Finder" plugin and yours.
Moreover, I've tried "Quick Finder" and I didn't manage to make it work.
_(my searches didn't return any results..)_

Your plugin has a different approach (_no "buffer" sqlite database_ ) and some basic regex features.
It seems interesting!
I would try submit again to QGIS plugin manager.

By the way, I use your other "Lat Long plugin" and I would like to say thank you for this great work.
Works perfectly without any bug and features are really neat! Congrats!

**Comment by NyakudyaA** [comment]
Do you still see the need for this plugin to be approved. There is a new core search functionality that is intergrated in core in QGIS 3.

**Comment by Fabien98** [comment]
As for me, I didn't try QGIS 3 yet.
if there is a relevant core search fonctionnality in this version,i'm fine with that.
However it's not possible to keep this plugin for legacy  purpose (QGIS 2.X  versions?)

**Comment by hamiltoncj** [comment]
Yes I think it is worth while especially for the 2.x QGIS. Keep in mind
that for production organizations the 2.x release will likely be used
between 2-4 years except for early adopters and even they may keep a 2.x
version around just in case. I have teams that are still using QGIS 2.8. I
don't think the 3.x will be used until it becomes a LTR and even then
perhaps not the first version.

**Comment by hamiltoncj** [comment]
I posted this knowing that the QGIS 3.0 search capability is supposed to be
better. I really released it for 2.x which I think will have a 2-4 year
life span. Incidentally, I have not been able to find the search capability
across all layers and all fields in 3.x. Where is it?
