### ISSUE TITLE
Uncaught NameError: global name 'showErrorMessage' is not defined


### ISSUE THREAD

**Issue by peter-shr** [NationalSecurityAgency/qgis-searchlayers-plugin#5]
Steps to reproduce
 1. First - Enter the search text (Neue Hütte)
 2. Second - contains
 3. Third - klick 'Search' Button

```
Traceback (most recent call last):
  File "C:/Users/USER/.qgis2/python/plugins\searchlayers\searchDialog.py", line 189, in workerError
    showErrorMessage(exception_string)
NameError: global name 'showErrorMessage' is not defined

```
searchlayers 0.2, QGIS 2.18.14 on Windows 10

**Comment by hamiltoncj** [comment]
Thank you for letting me know about this error. Although I was not able to replicate it exactly, I believe I found the errors that were causing it. I have uploaded version 0.2.1 to the QGIS plugin repo. It usually takes a few minutes before the catalog is update, but please test it out and let me know if you find any other problems.

Thanks for your help!!!
