### ISSUE TITLE
Datasecurity NSA

### ISSUE THREAD

**Issue by filipmahieu** [NationalSecurityAgency/qgis-searchlayers-plugin#6]
Hello,

in Europe (Belgium) the NSA has a doubtfull image concerning datasecurity. We are in doubt in using this plugin because of possible hacking of our governal data. It is code, after all.

We cannot be sure your plugin is safe for not exploring our data and transferring it to the NSA. 

How can we be sure your code and the updates of your codes are not malicious?

Greetings,

Filip Mahieu
Province East-Flanders
Belgium

**Comment by ctubbsii** [comment]
Hello @filipmahieu,

You seem to be asking for warranties, and I think that it would be very unusual for any open source project to grant such warranties as those you appear to have requested. This project appears to be provided under the GPL 2.0 license, which explicitly disclaims any such warranties (as do all open source licenses I'm familiar with). However, it also provides you with the right to view, copy, modify, and redistribute all the source code... so you don't have to trust the source of the code if you do not wish to do so. This is no different than any other open source project under similar licenses.

Also, if anybody finds any buggy code (whether suspected of being malicious or not), they could just report it publicly here.
