### ISSUE TITLE
ObjectName not set

### ISSUE THREAD

**Issue by mclucky** [NationalSecurityAgency/qgis-searchlayers-plugin#7]
We are implementing a dynamic toolbar plugin and we decided to reference standard qgis tools as well as tools from other plugins by their ObjectName e.g. "mAction...".

Obviously, your tool currently does not set an ObjectName, will you provide it in the future?

**Comment by hamiltoncj** [comment]
@mclucky I'm not sure what is needed for an 'ObjectName'? How are you trying to implement this? Is there an example plugin that does what you need? I could look at it to see what they did.

The Search Layers plugin was written for 2.x to fill a lack in the search capabilities. QGIS 3 has greatly improved searching; however, it still does not search across all layers and all field. I have been debating whether I should port it to QGIS 3 or not. At that point I have not had any requests to do so.

**Comment by mclucky** [comment]
If you look at settings-customize you get the treeview with all toolbars, menus and tools.
The first column of this treeview is objectName. 
Most of the actions use an objectName like "mAction...". 
We make use of that concept and reference standard tools and tools of other plugins by their objectName property. You can set it with setObjectName.

Regarding QGIS 3, we are currently migrating our own plugin too. If you will provide your plugin for QGIS 3 we would appreciate it.

**Comment by hamiltoncj** [comment]
I see Search Layers under Menus->mPluginMenu->SearchLayers. It is also under Toolbars->mPluginToolBar->SearchLayers so it is there, but am I missing something.

**Comment by mclucky** [comment]
I'll provide you a screenshot, there you see it. Your tools did not provide an ObjectName, there is an empty string. Most of the other plugin tools as well as QGIS standard tools provide an ObjectName. @
![unbenannt](https://user-images.githubusercontent.com/7901812/40772384-19391c1e-64c0-11e8-848c-99a81d197400.png)

**Comment by hamiltoncj** [comment]
Thanks for that. It looks like very few plugin developers outside of the core plugins have given object names. I just uploaded version 0.2.2 of the Search Layers plugin. If you have contacted others, I'm sure it would be useful to them to know how to fix this by telling them to add the object name right after they create the menu actions ie. self.action.setObjectName('pluginActionObjectName')

It may take a few minutes before the plugin repo is updated to reflect the 0.2.2 update. Let me know if this solves this issue.

**Comment by mclucky** [comment]
Thank you for fixing this issue and gave us this hint.
Now everything works as expected and we're able to reference your tool with the given ObjectName.
